insert into Tipo_de_atendimento(tipo_de_atendimento_id,nome,duracao_esperada,efeitos_colaterais,preco) values
(default, "Ressonância magnetica na região da cabeça", "00:35:00", "Não possui efeitos colaterais.",1000),
(default, "Acupuntura", "01:15:00", "Não possui efeitos colaterais.",2323),
(default, "Cirurgia", "04:35:00", "Possui riscos de efeitos colaterais de perda de movimento da mão, perda do movimento dos dedos.",34433),
(default, "Cirurgia Torácica", "08:20:00", "O principal efeito colateral da simpatectomia é o chamado efeito compensatório. Esse efeito é descrito quando ocorrem episódios de sudorese em outras partes do corpo que não eram habituais antes da cirurgia. Habitualmente, o efeito compensatório ocorre no tronco, pernas, abdome, coxas, virilhas, pés e glúteos. O efeito compensatório tem grande relevância, pois seu grau de intensidade influencia diretamente a qualidade de vida do paciente.",3433),
(default, "Consulta períodica", "0:30:00", "Não possui efeitos colaterais",433433),
(default, "Cirurgia Vascular", "01:30:00", "Possui riscos de inchaço e escoriações",34322),
(default, "Fisioterapia para as pernas", "00:25:00", "Não possui efeitos colaterais",6543),
(default, "Consulta periódica", "05:0:00", "O paciente pode sentir dor leve no momento da punção da fístula com as agulhas. Quanto aos efeitos colaterais, no geral, os pacientes são sentem nada, mas pode ocorrer queda da pressão arterial, câimbras ou dor de cabeça.",54233),
(default, "Quimioterapia", "02:20:00", "O tratamento com quimioterapia pode causar diferentes efeitos colaterais, como queda de cabelo, diarreia, feridas na boca, náuseas e vômitos, pele sensível e até mesmo infertilidade.",34334),
(default, "Consulta", "00:45:00", "Não possui efeitos colaterais",98765),
(default, "Quimioterapia", "00:40:00", "O tratamento com quimioterapia pode causar diferentes efeitos colaterais, como queda de cabelo, diarreia, feridas na boca, náuseas e vômitos, pele sensível e até mesmo infertilidade.",4565),
(default, "Diagnóstico e tratamento da doença renal crônica", "01:50:00", "Não possui efeitos colaterais",6453),
(default, "Cirurgia", "08:15:00", "As complicações neurológicas incluem diminuição do nível de consciência, vasoespasmo, convulsões, hipertensão intracraniana, déficits motores, entre outros. Já as complicações sistêmicas incluem náuseas e vômitos, hipotensão, desconforto respiratório e infecção do sítio cirúrgico, dor e infecções nosocomiais.",2455),
(default, "Consulta", "00:30:00", "Não possui efeitos colaterais",2353),
(default, "Consulta", "00:25:00", "Não possui efeitos colaterais",235235),
(default, "Consulta", "00:55:00", "Não possui efeitos colaterais",32676),
(default, "Remoção das pedras nos rins", "04:15:00", "É comum sentir uma dor lombar aguda, unilateral, que tende a se deslocar para as partes mais baixas do abdome. Em alguns casos, os homens também sofrem um desconforto nos testículos e as mulheres, nos grandes lábios.",641236),
(default, "Examinação das  glândulas", "00:30:00", "Não possui efeitos colaterais",5643445),
(default, "Diagnóstico de doenças cardiovasculares", "01:30:00", "Não possui efeitos colaterais",43544531),
(default, "Cirurgia bariátrica", "09:15:00", "Alguns efeitos colaterais, dependendo do tipo de cirurgia, são até comuns. Nos meses imediatamente posteriores à operação, relatos de perda leve de memória, irritação e insônia tornam-se habituais em hospitais e consultórios",53632),
(default, "Transplante de fígado", "04:40:00", "Com o uso de imunossupressores podem surgir sintomas como inchaço corporal, aumento do peso, aumento da quantidade de pelos no corpo, especialmente no rosto das mulheres, osteoporose, má digestão, queda de cabelo e aftas. Assim, deve-se observar os sintomas que aparecem e conversar com o médico para que ele indique o que se pode fazer para controlar estes sintomas desagradáveis, sem prejudicar o esquema de imunossupressão.",4543),
(default, "Acompanhamento médico", "0:35:00", "Não possui efeitos colaterais",64334),
(default, "Consulta", "00:50:00", "Não possui efeitos colaterais",64324),
(default, "Ultrassom", "00:25:00", "Não possui efeitos colaterais",98765),
(default, "Cirurgia na região bucal", "00:15:00", " O edema ou inchaço pode ocorrer em maior, ou menor grau dependendo da pessoa;Dor no local. Devido à intervenção, é comum que o local fique bastante dolorido; Cicatrização. O processo de cicatrização é relativo e pode demorar mais ou menos dependendo da pessoa; Trismo; Mau hálito; Parestesia; Dores de garganta.",324567),
(default, "Terapia", "00:50:00", "Não possui efeitos colaterais",123456),
(default, "Substituição de uma medula óssea", "06:50:00", "Náusea e vômito; Feridas na boca; Fadiga; Níveis baixos de plaquetas, dificultando a coagulação do sangue; Níveis baixos de glóbulos vermelhos, causando anemia; Diarreia.",1234567890),
(default, "Cirurgia", "10:15:00", "Os efeitos colaterais pós-cirúrgicos costumam desaparecer por volta dos primeiros 7 a 10 dias. A maioria dos pacientes se queixa de irritação ou sensação leve de areia nos olhos, coceira e sensibilidade a luz. ",34345),
(default, "Quimioterapia", "00:40:00", "O tratamento com quimioterapia pode causar diferentes efeitos colaterais, como queda de cabelo, diarreia, feridas na boca, náuseas e vômitos, pele sensível e até mesmo infertilidade.",64533);$$



insert into Tipo_de_tratamento values
(14, 0, default, "Ressonância"),
(6, 0, default, "Acupuntura"),
(2, 0, default, "Cirurgia da Mão"),
(2, 1, default, "Simpatectomia"),
(25, 0, default, "Cirurgia Plástica"),
(2, 1, default, "Angiologia"),
(10, 1, default, "Fisioterapia"),
(5, 1, default, "Hemodiálise"),
(2, 1, default, "Cancer no estomago"),
(3, 0, default, "Terapia pseudocientífica"),
(3, 1, default, "Cancer de pele"),
(3, 1, default, "Prevenção de doenças renais"),
(8, 1, default, "Cirurgia neurológica"),
(9, 0, default, "Nutrologia"),
(10, 0, default, "Rinologia"),
(18, 0, default, "Psiquiatria"),
(7, 1, default, "Cálculo renal"),
(4, 0, default, "Endocrinologia Pediátrica"),
(2, 0, default, "Ergometria"),
(1, 1, default, "Gastroplastia"),
(1, 1, default, "Hepatologia"),
(15, 0, default, "Neonatologia"),
(3, 0, default, "Psicogeriatria"),
(4, 0, default, "Pré-Natal"),
(4, 0, default, "Remoção de siso"),
(6, 0, default, "Psicólogo"),
(3, 1, default, "Transplante de Medula Óssea"),
(8, 1, default, "Tranplante de córnea"),
(12, 1, default, "Cancer no pulmão");$$


insert into especialidade values 
("Acupuntura", default),
("Alergia e Imunologia", default),
("Anestesiologia",default),
("Angiologia",default),
("Cancerologia",default),
("Cardiologia",default),
("Cirurgia Cardiovascular",default),
("Cirurgia da Mão",default),
("Cirurgia de Cabeça e Pescoço",default),
("Cirurgia do Aparelho Digestivo",default),
("Cirurgia Geral",default),
("Cirurgia Pediátrica",default),
("Cirurgia Plástica",default),
("Cirurgia Torácica",default),
("Cirurgia Vascular",default),
("Clínica Médica", default),
("Coloproctologia",default),
("Dermatologia",default),
("Endocrinologia e Metabologia",default),
("Endoscopia",default),
("Gastroenterologia",default),
("Genética Médica",default),
("Geriatria",default),
("Ginecologia e Obstetrícia",default),
("Hematologia e Hemoterapia",default),
("Homeopatia",default),
("Infectologia",default),
("Mastologia", default),
("Medicina de Família e Comunidade", default),
("Medicina do Trabalho", default),
("Medicina de Tráfego",default),
("Medicina Esportiva",default),
("Medicina Física e Reabilitação",default),
("Medicina Intensiva",default),
("Medicina Legal e Perícia Médica",default),
("Medicina Nuclear",default),
("Medicina Preventiva e Social",default),
("Nefrologia",default),
("Neurocirurgia",default),
("Neurologia",default),
("Nutrologia",default),
("Oftalmologia",default),
("Oncologia",default),
("Ortopedia e Traumatologia",default),
("Otorrinolaringologia",default),
("Patologia",default),
("Pediatria",default),
("Pneumologia",default),
("Psiquiatria",default),
("Radiologia e Diagnóstico por Imagem",default),
("Radioterapia",default),
("Reumatologia",default),
("Urologia",default),
("Administração em Saúde",default),
("Alergia e Imunologia Pediátrica",default),
("Angiorradiologia e Cirurgia Endovascular",default),
("Atendimento ao queimado",default),
("Cardiologia Pediátrica",default),
("Cirurgia Crânio-Maxilo-Facial",default),
("Cirurgia do Trauma",default),
("Cirurgia Videolaparoscópica",default),
("Citopatologia",default),
("Densitometria Óssea",default),
("Dor",default),
("Ecocardiografia",default),
("Ecografia Vascular com Doppler",default),
("Eletrofisiologia Clínica Invasiva",default),
("Endocrinologia Pediátrica",default),
("Endoscopia Digestiva",default),
("Endoscopia Ginecológica",default),
("Endoscopia Respiratória",default),
("Ergometria",default),
("Foniatria",default),
("Gastroenterologia Pediátrica",default),
("Hansenologia",default),
("Hematologia e Hemoterapia Pediátrica",default),
("Hemodinâmica e Cardiologia Intervencionista",default),
("Hepatologia",default),
("Infectologia Hospitalar",default),
("Infectologia Pediátrica",default),
("Mamografia",default),
("Medicina de Urgência",default),
("Medicina do Adolescente",default),
("Medicina do Sono",default),
("Medicina Fetal",default),
("Medicina Intensiva Pediátrica",default),
("Medicina Paliativa",default),
("Medicina Tropical",default),
("Nefrologia Pediátrica",default),
("Neonatologia",default),
("Neurofisiologia Clínica",default),
("Neurologia Pediátrica",default),
("Neurorradiologia",default),
("Nutrição Parenteral e Enteral",default),
("Nutrição Parenteral e Enteral Pediátrica",default),
("Nutrologia Pediátrica",default),
("Pneumologia Pediátrica",default),
("Psicogeriatria",default),
("Psicoterapia",default),
("Psiquiatria da Infância e Adolescência",default),
("Psiquiatria Forense",default),
("Radiologia Intervencionista e Angiorradiologia",default),
("Reumatologia Pediátrica",default),
("Sexologia",default),
("Transplante de Medula Óssea",default),
("Ultrassonografia em Ginecologia e Obstetrícia",default);$$

insert into compete values 
(1,16),
(2,1),
(3,8),
(4,14),
(5,13),
(6,4),
(7,44),
(8,16),
(9,43),
(10,26),
(11,43),
(12,38),
(13,40),
(14,41),
(15,45),
(16,49),
(17,38),
(18,68),
(19,72),
(20,21),
(21,78),
(22,93),
(23,98),
(24,23),
(25,11),
(26,100),
(27,105),
(28,42),
(29,43);